name: Testing stuff

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]


jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Shouldn't run if skip in commit
        env:
          TEST: ${{ contains(join(github.event.commits.*.message, ', '), '#skip') }}

        if: ${{ !contains(github.event.commits.*.message, '#skip') }}
        run: echo The step ran && echo $TEST